### ISSUE TITLE
community.zabbix.zabbix_host does not update host_groups properly

### ISSUE THREAD

**Issue by Julien5858** [zabbix/ansible-collection#14]
Hello,

While using the zabbix_host module, we noticed that when an existing host_group is removed from a host in Ansible, it did not get reflected in Zabbix so we have to remove them by hand, is this something the module cannot handle yet?

Note that we are using an old version of the module and haven't tried to update yet:

```
- name: community.zabbix
    version: 1.9.3_
```

```
- name: Update an existing host's info
  community.zabbix.zabbix_host:
    host_name: "{{ zabbix_host_host_name }}"
    state: "{{ zabbix_host_state }}"
    visible_name: "{{ zabbix_host_visible_name }}"
    description: "{{ zabbix_host_description }}"
    host_groups: "{{ (zabbix_host_host_groups + zabbix_host_host_groups_defaults | flatten + _zabbix_host_do_no_monitor | default()) | sort | unique | select() }}"
    link_templates: >
      {{
        (
          ( zabbix_host_previous_templates.json.result[0].parentTemplates | json_query('[].name') | list )
          + _zabbix_host_link_templates
          | flatten
        ) | sort | unique
      }}
    status: "{{ zabbix_host_status }}"
    interfaces: "{{ zabbix_host_interfaces }}"
    inventory_mode: "{{ zabbix_host_inventory_mode }}"
    inventory_zabbix: "{{ zabbix_host_inventory_zabbix }}"
    ipmi_authtype: "{{ zabbix_host_ipmi_authtype }}"
    ipmi_privilege: "{{ zabbix_host_ipmi_privilege }}"
    ipmi_username: "{{ zabbix_host_ipmi_username }}"
    ipmi_password: "{{ zabbix_host_ipmi_password }}"
    proxy: "{{ zabbix_host_proxy }}"
    macros: "{{ _zabbix_host_macros }}"
    tags: "{{ zabbix_host_tags }}"
    server_url: "{{ zabbix_host_server_url }}"
    login_user: "{{ zabbix_host_login_user }}"
    login_password: "{{ zabbix_host_login_password }}"
    force: "{{ zabbix_host_force }}"
    timeout: "{{ zabbix_host_api_timeout }}"
  delegate_to: localhost
```
