### ISSUE TITLE
RHEL 9.5 failing "assertion: repository_internal_supported_os is true"

### ISSUE THREAD

**Issue by MKletz** [zabbix/ansible-collection#17]
Getting the following error. Ansible core 2.16.14 via AAP 2.5. This seems to imply RHEL 9.5 is not supported on some internal list. But is listed on the agent [page](https://www.zabbix.com/download?zabbix=7.2&os_distribution=red_hat_enterprise_linux&os_version=9&components=agent_2&db=&ws=)

```
evaluated_to: false
assertion: repository_internal_supported_os is true
msg: Assertion failed
_ansible_no_log: false
changed: false
```

```
  roles:
    - role: zabbix.zabbix.agent
      agent_variant: 2
      agent_major_version: 7.2
      agent_param_server: "{{ zabbix_server }}"
      agent_param_serveractive: "{{ zabbix_server }}"
      agent_param_hostmetadata: 'RHEL Servers'
```
