### ISSUE TITLE
Zabbix.host returns ImportError: cannot import name 'CertificateError'

### ISSUE THREAD

**Issue by microkc** [zabbix/ansible-collection#8]
I have a playbook setup to install the zabbix agent and add the agent to my zabbix server but I am getting an error when it gets to the hostgroup presence step.  The agent part of the playbook works correctly.  I initially though it was due to my zabbix server being behind a reverse proxy for https with certificate offloading but I change the config and tried using it without the reverse proxy and still receive the error.  

I have tried with host_zabbix_api_use_ssl set to both true and false, I also have host_zabbix_api_validate_certs set to false.  I posted on the zabbix forum but did not receive a response.

I am running the latest version of ansible (core 2.17.0)  I am running Zabbix server 7.0.0 on debian 12.

Any help is appreciated.

**Comment by atocko** [comment]
Looks like python library conflict on Ansible controller side.
Try creating fresh virtual environment and install only libraries, that the collection depends.
Thanks for feedback!

**Comment by atocko** [comment]
Fixing ASAP, wait pls

**Comment by atocko** [comment]
Published version 1.3.10 on galaxy
It adds 2.17 core support and removes CertificateError exception error.
Feel free to update.

**Comment by atocko** [comment]
Maybe i missed something, but it looks like you are trying to use zabbix_host module outside of our host role.
There is a trick to work with modules, that uses ansible http plugin. Api location should be placed to an 'delegate_to' filed :)
Take a look at our zabbix.zabbix.host role sources: 
https://github.com/zabbix/ansible-collection/blob/main/roles/host/tasks/main.yml

**Comment by atocko** [comment]
Hey Susan!
By default **zabbix.zabbix.host** role uses **ansible_host** variable from inventory. Role checks if its IP addres and places it to the IP field. If not -> DNS.
Check the readme of host role for the default values to get basic understanding of what is going on.

Set an **ansible_host** variable in your inventory for the hosts :)

Here is example of inventory file in yaml format:
```yaml
Linux Servers:
  hosts:
    10.2.1.27:
      ansible_host: 10.2.1.27
      ansible_user: someuser
      ansible_become_password: somepassword
```
I'm actually reusing the name of host in inventory to avoid repeating the address:
```yaml
Linux Servers:
  hosts:
    10.2.1.27:
      ansible_host: '{{ inventory_hostname }}'
      ansible_user: someuser
      ansible_become_password: somepassword
```
But having a proper name for the host instead of ip could be more readable :)

We will update documentation to be more clear about it next time.
